# @package _global_
defaults:
  - paths: default
  - model: synthetic
  - datamodule: synthetic
  - trainer: default
  - logger: csv
  - experiment: null
  - _self_

hydra:
  run:
    dir: ${paths.output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}-eval

experiment_name: eval
